# Generated by Django 3.1.7 on 2021-03-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('speciality', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('area', models.CharField(default='', max_length=50)),
                ('region', models.CharField(default='', max_length=50)),
                ('fees', models.IntegerField(default=0)),
                ('visitingtime', models.CharField(default='', max_length=300)),
                ('shortdiscription', models.CharField(default='', max_length=10000)),
                ('Email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('Dateofbirth', models.DateField()),
                ('image', models.ImageField(default='', upload_to='doctor/images')),
            ],
        ),
    ]
